import { User } from './users.model';
import { IUser } from './user.schema'
import { generateUserId } from './user.utils';
import config from '../../../config/index';
import ApiError from '../../../errors/ApiErrors';
const createUser = async (user: IUser):Promise<IUser | null> => {
    // Autogenerated incremental id
    const id = await generateUserId();
    user.id = id;

    // Default Password
    if(!user.password){
        user.password = config.default_student_password as string;
    }

    const createdUser = await User.create(user);
    if(!createdUser){
        throw new ApiError(400, 'Failed to create user');
    }
    return createdUser;
}

export default {
    createUser
}